
namespace AotForms
{
    internal static class WeaponIconData
    {
        internal static Dictionary<uint, string> WeaponIconNames = new Dictionary<uint, string>
        {

            { 1, string.Empty }, 
            { 16, nkvt.Pan }, 
            { 17, nkvt.Parang },
            { 27, nkvt.Bat }, 
            { 34, nkvt.Scythe }, 
            { 51, nkvt.Scythe },
            { 66, nkvt.Scythe }, 
            { 68, nkvt.Scythe },
            { 84, nkvt.Scythe }, 
            { 85, nkvt.Parang }, 
            { 87, nkvt.Scythe }, 
            { 132, nkvt.FFKnife }, 
            { 133, nkvt.FFKnife }, 
            { 134, nkvt.FFKnife }, 
            { 135, nkvt.Bat }, 
            { 136, nkvt.Bat }, 
            { 137, nkvt.Pan }, 
            { 138, nkvt.Bat }, 
            { 139, nkvt.Bat }, 
            { 176, nkvt.Scythe }, 
            { 177, nkvt.Bat }, 

            { 3, nkvt.USP }, 
            { 9, nkvt.DesertEagle }, 
            { 10, nkvt.G18 }, 
            { 20, nkvt.M1873 }, 
            { 25, nkvt.M500 }, 
            { 44, nkvt.M500 }, 
            { 52, nkvt.DesertEagle }, 
            { 53, nkvt.DesertEagle }, 
            { 55, nkvt.M1917 }, 
            { 56, nkvt.USP2 }, 
            { 58, nkvt.Uzi }, 
            { 93, nkvt.HealPistol }, 
            { 21001, nkvt.HealPistol }, 
            { 100, nkvt.Flamethrower }, 
            { 101, nkvt.USP }, 
            { 147, nkvt.DesertEagle }, 
            { 159, nkvt.G18 }, 
            { 162, nkvt.M500 }, 
            { 170, nkvt.M1873 }, 
            { 187, nkvt.M500 }, 
            { 188, nkvt.M500 }, 
            { 189, nkvt.M500 }, 
            { 190, nkvt.Flamethrower }, 
            { 191, nkvt.Flamethrower }, 
            { 192, nkvt.Flamethrower }, 

            { 4, nkvt.AWM }, 
            { 65, nkvt.AWM }, 
            { 21, nkvt.Kar98k }, 
            { 64, nkvt.Kar98k }, 
            { 78, nkvt.HealSniper }, 
            { 94, nkvt.AWM }, 
            { 95, nkvt.SVD }, 
            { 96, nkvt.AWM }, 
            { 97, nkvt.M82B }, 
            { 98, nkvt.AWM }, 
            { 128, nkvt.Kar98k }, 
            { 129, nkvt.Kar98k }, 
            { 45, nkvt.M82B }, 
            { 75, nkvt.M24 }, 
            { 142, nkvt.AWM }, 
            { 154, nkvt.Kar98k }, 
            { 165, nkvt.M82B }, 
            { 197, nkvt.VSK94 }, 
            { 198, nkvt.AWM }, 

            { 5, nkvt.M1014 }, 
            { 29, nkvt.Spas }, 
            { 41, nkvt.M1887 }, 
            { 50, nkvt.Mag7 }, 
            { 69, nkvt.M1887 }, 
            { 86, nkvt.ChargeBuster }, 
            { 119, nkvt.M1887 }, 
            { 143, nkvt.M1887 }, 
            { 157, nkvt.Spas }, 
            { 168, nkvt.Mag7 }, 
            { 173, nkvt.M1014 }, 
            { 181, nkvt.Trogon }, 
            { 182, nkvt.ChargeBuster }, 
            { 183, nkvt.Trogon }, 
            { 184, nkvt.M1014 }, 
            { 185, nkvt.M1014 }, 
            { 186, nkvt.M1014 }, 
            { 21002, nkvt.M590 }, 

            { 7, nkvt.UMP }, 
            { 8, nkvt.MP5 }, 
            { 13, nkvt.VSS }, 
            { 15, nkvt.MP40 }, 
            { 32, nkvt.P90 }, 
            { 35, nkvt.CG15 }, 
            { 40, nkvt.Vector }, 
            { 42, nkvt.MP5 }, 
            { 43, nkvt.Thompson }, 
            { 49, nkvt.Vector }, 
            { 59, nkvt.P90 }, 
            { 60, nkvt.MP5 }, 
            { 62, nkvt.VSS }, 
            { 88, nkvt.Mac10 }, 
            { 120, nkvt.MP5 }, 
            { 121, nkvt.MP5 }, 
            { 125, nkvt.VSS }, 
            { 141, nkvt.MP5 }, 
            { 150, nkvt.Bizon }, 
            { 151, nkvt.Vector }, 
            { 152, nkvt.VSS }, 
            { 153, nkvt.MP40 }, 
            { 155, nkvt.UMP }, 
            { 160, nkvt.P90 }, 
            { 164, nkvt.Thompson }, 
            { 166, nkvt.Mac10 }, 

            { 19, nkvt.M249 }, 
            { 30, nkvt.M60 }, 
            { 54, nkvt.M60 }, 
            { 61, nkvt.M60 }, 
            { 71, nkvt.M249 }, 
            { 122, nkvt.M60 }, 
            { 123, nkvt.M60 }, 
            { 146, nkvt.M60 }, 
            { 158, nkvt.M249 }, 
            { 172, nkvt.M60 }, 

            { 18, nkvt.SKS }, 
            { 23, nkvt.M82B }, 
            { 26, nkvt.SVD }, 
            { 31, nkvt.SVD }, 
            { 48, nkvt.Woodpecker }, 
            { 72, nkvt.SVD }, 
            { 89, nkvt.AC80 }, 
            { 126, nkvt.Woodpecker }, 
            { 161, nkvt.SVD }, 
            { 163, nkvt.Woodpecker }, 
            { 167, nkvt.SKS }, 
            { 196, nkvt.AC80 }, 

            { 2, nkvt.M4A1 }, 
            { 6, nkvt.AK47 }, 
            { 11, nkvt.M14 }, 
            { 12, nkvt.SCAR }, 
            { 14, nkvt.Groza }, 
            { 24, nkvt.FAMAS }, 
            { 28, nkvt.XM8 }, 
            { 33, nkvt.AN94 }, 
            { 36, nkvt.G36 }, 
            { 37, nkvt.M4A1 }, 
            { 38, nkvt.SCAR }, 
            { 39, nkvt.Plasma }, 
            { 46, nkvt.AUG }, 
            { 47, nkvt.ParaFAL }, 
            { 57, nkvt.Kingfisher }, 
            { 63, nkvt.M14 }, 
            { 67, nkvt.FAMAS }, 
            { 70, nkvt.Groza }, 
            { 73, nkvt.G36 }, 
            { 74, nkvt.G36 }, 
            { 79, nkvt.G36 }, 
            { 80, nkvt.M4A1 }, 
            { 81, nkvt.M4A1 }, 
            { 82, nkvt.M4A1 }, 
            { 83, nkvt.XM8 }, 
            { 99, nkvt.Plasma }, 
            { 124, nkvt.M14 }, 
            { 127, nkvt.M14 }, 
            { 130, nkvt.FAMAS }, 
            { 131, nkvt.FAMAS }, 
            { 140, nkvt.M4A1 }, 
            { 144, nkvt.AK47 }, 
            { 145, nkvt.Groza }, 
            { 148, nkvt.SCAR }, 
            { 149, nkvt.M14 }, 
            { 156, nkvt.XM8 }, 
            { 169, nkvt.AN94 }, 
            { 171, nkvt.AUG }, 
            { 174, nkvt.FAMAS }, 
            { 175, nkvt.ParaFAL }, 
            { 178, nkvt.SCAR }, 
            { 179, nkvt.SCAR }, 
            { 180, nkvt.SCAR }, 
            { 193, nkvt.AUG }, 
            { 194, nkvt.AUG }, 
            { 195, nkvt.AUG }, 
            { 199, nkvt.M4A1 }, 
            { 200, nkvt.AK47 }, 

            { 76, nkvt.Grenade }, 
            { 77, nkvt.Smoke }, 
            { 90, nkvt.Plasma }, 
            { 91, nkvt.Grenade }, 
            { 92, nkvt.Flashbang }, 
            { 102, nkvt.GlooWall } 
        };

        public static string GetIconForWeaponId(uint weaponId)
        {
            if (weaponId == 0)
                return string.Empty;

            if (WeaponIconNames.TryGetValue(weaponId, out string icon))
                return icon;

            return string.Empty;
        }
    }
}